//DOM
//Document Object Model

//Hirarki
//Root
//Prent=>child=Sibling
// let judul = document.querySelector('h1')
// let judul = document.querySelectorAll('h1')

// console.log(judul);
// judul[0].style.fontSize = '90px'
// judul[1].style.color = 'grey'
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// let list = document.querySelectorAll('li')
    
// console.log(list);
// for(let bakso = 0; bakso<list.length;bakso++){
    
//         list[bakso].style.fontSize = '30px'
//     }
// console.log(bakso)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

